### ISSUE TITLE
App crash on start after install. 

### ISSUE THREAD

**Issue by archie94** [sunny5125/pdm#48]
This bug is caused by permission restrictions on first launch of the app. For now the fix is to manually allow all permissions to the app from Settings.

**Comment by archie94** [comment]
@ghoshbishakh What was the fix?

**Comment by ghoshbishakh** [comment]
@archie94 no idea XD I thought it was already fixed. Let me repoen it for verification!

**Comment by archie94** [comment]
@ghoshbishakh Steps to reproduce:
- Install pdm on your phone. 
- On first run you will see that the app crashes, essentially due to permission issues. We have to manually give all permissions from settings to get the app running. 
- we are requesting for all the permissions in the first activity, yet somehow the bug remains. This was introduced after we integrated the nextgis app.
- my idea is that we need an application class to request for all the permissions. But not sure on this.

**Comment by ghoshbishakh** [comment]
@archie94 Got that! **Manual permissions needed**!

**Comment by namanmehta1997** [comment]
@archie94 Is this issue there for the devices < Android M?

**Comment by sunysaurav** [comment]
@namanmehta1997 NO , this only happen in run time permission is required . So only crash in >M .

**Comment by ghoshbishakh** [comment]
@sunny5125 yes. issue clear.

**Comment by archie94** [comment]
@namanmehta1997 what was the fix?

**Comment by ghoshbishakh** [comment]
@archie94 removing the entire GIS part 😆

**Comment by namanmehta1997** [comment]
@archie94,  We removed the GIS and chat module for the stability of the app. We shall add it later as a module, not as an app (Hopefully that will solve our issues). But for the time being this is not the part of the app so I closed this issue

**Comment by archie94** [comment]
Cool! 👍  Please keep the GIS features in a branch. I may try to play with it if I have the time. :P
